name = "karib"
main = ".open-next/worker.js"
compatibility_date = "2025-06-01"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
pages_build_output_dir = ".open-next/assets"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
